# "service" is the name of this project. This will also be added to your AWS resource names.
service: hnb-exchange-tracker

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  stage: dev
  environment:
    BOT_TOKEN: ${ssm:/exchange-rate/BOT_TOKEN}
    CHAT_ID: ${ssm:/exchange-rate/CHAT_ID}
    RETRY_RULE_NAME: RetryHandlerScheduleRule
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "events:EnableRule"
        - "events:DisableRule"
      Resource:
        - arn:aws:events:${self:provider.region}:${aws:accountId}:rule/RetryHandlerScheduleRule

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: cron(50 3 ? * MON-FRI *)  # This runs at 3.50 AM UTC MON-FRI

  retryHandler:
    handler: handler.run
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: false # will be enabled only when needed
          name: RetryHandlerScheduleRule
